import { Brand, Creator, OutreachRow, TrybeCreator, BRANDS, identityKey, normalizeHandle, qualifies } from './model'
const now = new Date().toISOString()
const samples: Partial<OutreachRow>[] = [
 {brand:'ljco',creator_name:'Maya Torres',handle_raw:'@mayamakes',platform:'Instagram',followers:48200,email:'maya@example.com',segments:['foodie','outdoors'],contact_status:'Interested',deliverable_ask:'Unboxing reel + story',shipping_address:'221 Main St, Louisville, KY 40202',product_sku_sent:'Original Jerky Variety',deliverable_status:'Submitted',content_link:'https://example.com/maya',notes:'Content received for review.'},
 {brand:'ljco',creator_name:'Drew Calder',handle_raw:'@drewtrails',platform:'TikTok',followers:12500,email:'drew@example.com',segments:['outdoors'],contact_status:'Contacted',deliverable_ask:'Trail snack video',deliverable_status:'Not Started',notes:'Awaiting reply.'},
 {brand:'pumps',creator_name:'Riley Chen',handle_raw:'@rileylifts',platform:'Instagram',followers:71400,email:'riley@example.com',segments:['fitness'],contact_status:'Onboarded',deliverable_ask:'Gym bag snack feature',shipping_address:'45 Oak Ave, Chicago, IL 60601',deliverable_status:'Approved',content_link:'https://example.com/riley'},
 {brand:'pumps',creator_name:'Jordan Ellis',handle_raw:'@jordaneats',platform:'TikTok',followers:28700,email:'jordan@example.com',segments:['foodie'],contact_status:'Replied',deliverable_ask:'Recipe integration',deliverable_status:'In Progress'},
 {brand:'gym_snack',creator_name:'Riley Chen',handle_raw:'@rileylifts',platform:'Instagram',followers:71400,email:'riley@example.com',segments:['fitness'],contact_status:'Onboarded',deliverable_ask:'Post-workout taste test',shipping_address:'45 Oak Ave, Chicago, IL 60601',deliverable_status:'Posted',content_link:'https://example.com/riley-gym'},
 {brand:'gym_snack',creator_name:'Sam Rivera',handle_raw:'@samwellness',platform:'YouTube',followers:19200,email:'sam@example.com',segments:['fitness','wellness'],contact_status:'Interested',deliverable_ask:'Short review',shipping_address:'90 Pine Rd, Austin, TX 78701',deliverable_status:'In Progress'}
]
export function emptyRow(brand:Brand):OutreachRow {
 return {id:crypto.randomUUID(),brand,creator_name:'',date_first_contacted:null,handle_raw:'',handle_normalized:'',platform:null,followers:null,email:'',segments:[],contact_status:'Not Contacted',deliverable_ask:'',shipping_address:'',product_sku_sent:'',tracking_carrier:null,tracking_number:'',tracking_est_delivery:null,tracking_delivered:false,deliverable_status:'Not Started',content_link:'',date_posted:null,partnership_terms:'',ad_code:'',notes:'',source:'manual',created_at:now,updated_at:now}
}
export function seedRows():OutreachRow[] { return samples.map((sample)=>{const row={...emptyRow(sample.brand as Brand),...sample};row.handle_normalized=normalizeHandle(row.handle_raw||'');return row}) }
const firstNames=['Avery Morgan','Casey Brooks','Taylor Reed','Morgan Blake','Alex Rivera','Jamie Park','Cameron Wells','Parker Lane','Quinn Harper','Bailey Stone']
export function mockTrybe(brand:Brand):TrybeCreator[] { return firstNames.map((name,i)=>({id:`${brand}-${i}`,brand,trybe_creator_id:`${brand}-${1001+i}`,creator_name:name,joined:`2026-${String(1+(i%8)).padStart(2,'0')}-${String(10+i).padStart(2,'0')}`,program:i%3?'Affiliate':'Ambassador',commission:`${10+(i%3)*5}%`,status:i%4===0?'Pending':'Active',active:true})) }
export function demoCreators(rows:OutreachRow[], sticky:Record<string,string>, archived:OutreachRow[]=[]):Creator[] {
 const grouped = new Map<string,OutreachRow[]>()
 for(const row of [...rows,...archived]) if(qualifies(row) || sticky[row.id]) { const key=identityKey(row); grouped.set(key,[...(grouped.get(key)||[]),row]) }
 return [...grouped].map(([creator_key,items])=>{const latest=[...items].sort((a,b)=>b.updated_at.localeCompare(a.updated_at))[0];return {creator_key,creator_name:latest.creator_name,handle:latest.handle_raw,platform:latest.platform,email:latest.email,address:latest.shipping_address,brand_tags:[...new Set(items.map(i=>i.brand))].sort() as Brand[],first_qualified_at:sticky[items[0].id]||now,last_updated_at:latest.updated_at}})
}
export function readDemo():{rows:OutreachRow[];sticky:Record<string,string>;archived:OutreachRow[]} {try{const raw=localStorage.getItem('lb-crm-demo');if(raw){const saved=JSON.parse(raw);if(Array.isArray(saved.rows)&&saved.sticky)return {...saved,archived:saved.archived||[]}}}catch{} const rows=seedRows();return {rows,sticky:Object.fromEntries(rows.filter(qualifies).map(r=>[r.id,now])),archived:[]}}
export function saveDemo(rows:OutreachRow[],sticky:Record<string,string>,archived:OutreachRow[]) {try{localStorage.setItem('lb-crm-demo',JSON.stringify({rows,sticky,archived}))}catch{}}
export function applyOnboarding(rows:OutreachRow[],input:{full_name:string;handle:string;platform:string;email:string;shipping_address:string;brands:Brand[]}) {
 const updated=[...rows];for(const brand of input.brands){const match=updated.find(r=>r.brand===brand&&(r.email?.toLowerCase()===input.email.toLowerCase()||r.handle_normalized===normalizeHandle(input.handle)))
 if(match){const idx=updated.indexOf(match);const submittedAddress=input.shipping_address.trim(); updated[idx]={...match,creator_name:match.creator_name||input.full_name,handle_raw:match.handle_raw||input.handle,handle_normalized:match.handle_normalized||normalizeHandle(input.handle),platform:match.platform||input.platform,email:match.email||input.email.toLowerCase(),shipping_address:match.shipping_address||submittedAddress,notes:match.shipping_address&&match.shipping_address.trim()!==submittedAddress?`${match.notes?match.notes+'\n':''}Onboarding form submitted new address on ${new Date().toLocaleDateString()}: ${submittedAddress}`:match.notes,updated_at:now}}
 else updated.push({...emptyRow(brand),creator_name:input.full_name,handle_raw:input.handle,handle_normalized:normalizeHandle(input.handle),platform:input.platform,email:input.email.toLowerCase(),shipping_address:input.shipping_address,contact_status:'Onboarded',source:'onboarding_form'})}
 return updated
}
export const mockBrands = BRANDS
