import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowUpRight, X } from 'lucide-react'
import { DataTable, type GridColumn } from '../components/DataTable'
import { Brand, brandName, Creator, dateTime } from '../lib/model'
import { useStore } from '../lib/store'
export function Creators(){const {creators,rows,loading}=useStore();const [filter,setFilter]=useState('all'),[selected,setSelected]=useState<Creator|null>(null)
 const visible=filter==='all'?creators:creators.filter(c=>c.brand_tags.includes(filter as Brand))
 const columns=useMemo<GridColumn<Creator>[]>(()=>[
 {key:'creator_name',label:'Creator Name',width:210,render:r=><button className="text-link strong" onClick={()=>setSelected(r)}>{r.creator_name||r.handle||'Unnamed creator'} <ArrowUpRight size={14}/></button>},
 {key:'handle',label:'Handle',width:190},{key:'platform',label:'Platform',width:155},{key:'email',label:'Email',width:230},{key:'address',label:'Address',width:290},
 {key:'brand_tags',label:'Brand Tag',width:240,render:r=><div className="tag-list">{r.brand_tags.map(b=><span className="brand-tag" key={b}>{brandName[b]}</span>)}</div>}
 ],[])
 return <><div className="page-heading"><div><p className="eyebrow">DATABASE / DERIVED ROSTER</p><h1>Creator Database <span className="chip chip-warn">DERIVED · NEVER TYPED INTO</span></h1><p>Creators who have an address on file and have reached the content submission stage.</p></div></div><div className="metric-strip"><div><span>CREATORS</span><strong>{creators.length.toString().padStart(2,'0')}</strong></div><div><span>BRANDS</span><strong>03</strong></div><div className="strip-caption">One creator appears once, even across multiple brands.</div></div><section className="panel"><div className="panel-top"><div><p className="eyebrow">COMPANY ROSTER</p><h2>Creators worked with</h2></div><span className="panel-count">{visible.length} RECORDS</span></div>{loading?<p className="loading">Loading creators…</p>:<DataTable data={visible} columns={columns} filename="creator-database.csv" filters={<select className="filter-select" aria-label="Filter by brand" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All brands</option><option value="ljco">Louisville Jerky</option><option value="pumps">Pumps</option><option value="gym_snack">Gym Snack</option></select>} empty="No creator has crossed the gate yet."/>}<p className="table-legend">Fixing a record means fixing it on the Outreach tab it came from.</p></section>{selected&&<div className="drawer-overlay" onClick={()=>setSelected(null)}><aside className="detail-drawer" role="dialog" aria-modal="true" aria-label="Creator sources" onClick={e=>e.stopPropagation()}><div className="drawer-head"><p className="eyebrow">CREATOR SOURCES</p><button className="icon-btn" aria-label="Close" onClick={()=>setSelected(null)}><X size={19}/></button></div><h2>{selected.creator_name||selected.handle}</h2><p>{selected.email||'No email on file'}</p><div className="drawer-divider"/><h3>Outreach records</h3>{rows.filter(r=>r.email?.toLowerCase()===selected.creator_key||(!r.email&&`h:${r.handle_normalized}`===selected.creator_key)).map(r=><Link className="source-card" to={`/outreach/${r.brand}?row=${r.id}`} key={r.id}><span className="brand-tag">{brandName[r.brand]}</span><strong>{r.deliverable_status}</strong><small>Updated {dateTime(r.updated_at)}</small><ArrowUpRight size={16}/></Link>)}<p className="subtle">Previously qualified records remain in the roster if their source was deleted.</p></aside></div>}</>
}
