import { useMemo, useState, type ChangeEvent } from 'react'
import { AlertTriangle, ArrowRight, FileUp } from 'lucide-react'
import { Brand, brandName, BRANDS, CONTACT, DELIVERABLE, OutreachRow } from '../lib/model'
import { useStore } from '../lib/store'
import { duplicatesOf, mapRow, parseCsv, statusSuggestion, suggestColumn, type Mapping } from '../lib/importer'
const targets=[['drop','Drop column'],['unknown','Unmapped'],['creator_name','Creator Name'],['handle_raw','Handle'],['followers','Followers'],['email','Email'],['segments','Segments'],['contact_status','Contact Status'],['deliverable_status','Deliverable Status'],['deliverable_ask','Deliverable / Ask'],['shipping_address','Shipping Address'],['tracking_carrier','Carrier'],['tracking_number','Tracking Number'],['tracking_est_delivery','Est. Delivery'],['tracking_delivered','Delivered'],['date_first_contacted','Date First Contacted'],['date_posted','Date Posted'],['content_link','Content Link'],['platform','Platform'],['product_sku_sent','Product / SKU Sent'],['partnership_terms','Partnership Terms'],['ad_code','Ad Code'],['notes','Notes']]
export function ImportPage(){const {rows,importRows}=useStore();const [brand,setBrand]=useState<Brand>('ljco'),[source,setSource]=useState('Other'),[filename,setFilename]=useState(''),[matrix,setMatrix]=useState<string[][]>([]),[mapping,setMapping]=useState<Mapping>({}),[statusMap,setStatusMap]=useState<Record<string,string>>({}),[decisions,setDecisions]=useState<Record<number,'import'|'skip'|'merge'>>({}),[step,setStep]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const headers=matrix[0]||[],values=matrix.slice(1).filter(row=>row.some(Boolean))
 const unknownStatuses=useMemo(()=>{const result=new Map<string,{kind:'contact'|'deliverable';value:string}>();headers.forEach((_,i)=>{if(!['contact_status','deliverable_status'].includes(mapping[i]))return;const kind=mapping[i]==='contact_status'?'contact':'deliverable';values.forEach(row=>{const value=row[i]?.trim();if(value&&!statusSuggestion(value,kind))result.set(`${kind}:${value}`,{kind,value})})});return [...result]},[headers,values,mapping])
 const preview=useMemo(()=>values.map(row=>mapRow(row,headers,mapping,brand,statusMap)),[values,headers,mapping,brand,statusMap])
 function loadFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setFilename(file.name);file.text().then(text=>{const parsed=parseCsv(text.replace(/^\uFEFF/,''));setMatrix(parsed);const m:Mapping={};let blank=0;parsed[0]?.forEach((h,i)=>{m[i]=!h.trim()&&source==='GS Collabs'?['contact_status','deliverable_ask','tracking_delivered'][blank++]||'unknown':suggestColumn(h,i,source)});setMapping(m);setStep(1);setDecisions({})})}
 const existing=rows.filter(r=>r.brand===brand)
 const duplicates=preview.map((r,i)=>duplicatesOf(r,existing)||duplicatesOf(r,preview.slice(0,i)))
 async function commit(){setBusy(true);setMessage('');try{const records=preview.flatMap((r,i)=>{if(decisions[i]==='skip')return [];const {_warnings,...record}=r;return [{...record,_duplicateAction:decisions[i]==='merge'?'merge':'import'}]});await importRows(brand,records as Partial<OutreachRow>[]);setMessage(`Imported ${records.length} rows into ${brandName[brand]}.`);setStep(3)}catch(err){setMessage((err as Error).message)}finally{setBusy(false)}}
 return <><div className="page-heading"><div><p className="eyebrow">ADMINISTRATION / DATA MIGRATION</p><h1>Import old sheets <span className="chip chip-accent">ADMIN ONLY</span></h1><p>Map columns, resolve old statuses, and check every row before importing.</p></div></div><div className="stepper"><span className={step===0?'current':''}>01 Upload</span><span className={step===1?'current':''}>02 Map fields</span><span className={step===2?'current':''}>03 Preview</span><span className={step===3?'current':''}>04 Complete</span></div>{message&&<div className="sync-banner" role="status">{message}</div>}
 {step===0&&<section className="panel import-panel"><p className="eyebrow">SOURCE FILE</p><h2>Start with a CSV export</h2><p>Select a target brand and identify the source sheet. Nothing is saved until you confirm the preview.</p><div className="form-grid import-controls"><label>Target Outreach tab<select value={brand} onChange={e=>setBrand(e.target.value as Brand)}>{BRANDS.map(b=><option value={b} key={b}>{brandName[b]}</option>)}</select></label><label>Source sheet<select value={source} onChange={e=>setSource(e.target.value)}>{['Other','Native Partnerships · LJCo','LJCo Collabs','Native Partnerships · Pumps','Outreach · Pumps','Native Partnerships · Gym Snack','GS Collabs'].map(s=><option key={s}>{s}</option>)}</select></label></div><label className="upload-zone"><FileUp size={28}/><strong>Choose a CSV file</strong><span>Export the old Google Sheet as .csv first</span><input type="file" accept=".csv,text/csv" onChange={loadFile}/></label></section>}
 {step===1&&<section className="panel import-panel"><p className="eyebrow">FIELD MAPPING / {filename}</p><h2>Match old columns to Outreach</h2><p>{values.length} source rows. Confirm each suggested mapping. Repeated Notes columns will be combined.</p>{source==='GS Collabs'&&headers.some(h=>!h.trim())&&<div className="import-warning"><AlertTriangle size={17}/> GS Collabs has blank headers. Confirm their positions as Status, Samples Request?, and Delivered?.</div>}<div className="mapping-list">{headers.map((h,i)=><div key={i}><span>{h||`Blank column ${i+1}`}</span><span className="subtle">Example: {values.find(r=>r[i])?.[i]?.slice(0,35)||'Empty'}</span><select aria-label={`Map ${h||`blank column ${i+1}`}`} value={mapping[i]||'unknown'} onChange={e=>setMapping({...mapping,[i]:e.target.value})}>{targets.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>)}</div>{unknownStatuses.length>0&&<div className="status-map"><h3>Map unfamiliar status values</h3>{unknownStatuses.map(([key,item])=><label key={key}>{item.kind}: “{item.value}”<select value={statusMap[key]||''} onChange={e=>setStatusMap({...statusMap,[key]:e.target.value})}><option value="">Choose status</option>{(item.kind==='contact'?CONTACT:DELIVERABLE).map(s=><option key={s}>{s}</option>)}</select></label>)}</div>}<div className="import-buttons"><button className="button ghost" onClick={()=>setStep(0)}>Back</button><button className="primary" disabled={unknownStatuses.some(([key])=>!statusMap[key])} onClick={()=>setStep(2)}>Review preview <ArrowRight size={16}/></button></div></section>}
 {step===2&&<section className="panel import-panel"><p className="eyebrow">PREVIEW / {brandName[brand].toUpperCase()}</p><h2>Review {preview.length} rows</h2><p>Flagged rows can still be imported. Choose Skip or Merge for possible duplicates.</p><div className="preview-scroll"><table className="preview-table"><thead><tr><th>Row</th><th>Creator / Handle</th><th>Email</th><th>Status</th><th>Flags</th><th>Action</th></tr></thead><tbody>{preview.map((r,i)=><tr key={i}><td>{i+2}</td><td><strong>{r.creator_name||'Unnamed'}</strong><small>{r.handle_raw||'No handle'}</small></td><td>{r.email||'None'}</td><td>{r.contact_status||'None'}<small>{r.deliverable_status||'Not Started'}</small></td><td>{[...r._warnings,...(duplicates[i]?['Possible duplicate']:[])].map(w=><span className="warning-label" key={w}>{w}</span>)}</td><td><select aria-label={`Action for row ${i+2}`} value={decisions[i]||'import'} onChange={e=>setDecisions({...decisions,[i]:e.target.value as 'import'|'skip'|'merge'})}><option value="import">Import</option>{duplicates[i]&&<option value="merge">Merge</option>}<option value="skip">Skip</option></select></td></tr>)}</tbody></table></div><div className="import-buttons"><button className="button ghost" onClick={()=>setStep(1)}>Back to mapping</button><button className="primary" disabled={busy} onClick={()=>void commit()}>{busy?'Importing…':`Import ${preview.filter((_,i)=>decisions[i]!=='skip').length} rows`}</button></div></section>}
 {step===3&&<section className="panel import-panel"><h2>Import complete</h2><p>{message}</p><button className="button" onClick={()=>{setStep(0);setMatrix([]);setFilename('')}}>Import another file</button></section>}</>
}
