import { useState, type FormEvent } from 'react'
import { CheckCircle2, ArrowRight } from 'lucide-react'
import { Brand, brandName, BRANDS, emailValid, PLATFORM } from '../lib/model'
import { useStore } from '../lib/store'
export function Onboard(){const {onboard}=useStore();const [done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[brands,setBrands]=useState<Brand[]>([])
 const toggle=(brand:Brand)=>setBrands(brands.includes(brand)?brands.filter(b=>b!==brand):[...brands,brand])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=new FormData(e.currentTarget);if(form.get('website'))return setDone(true);if(!brands.length){setError('Choose at least one brand.');return}const email=String(form.get('email')||'').trim();if(!emailValid(email)){setError('Enter a valid email address.');return}setBusy(true)
 try{await onboard({full_name:String(form.get('full_name')).trim(),handle:String(form.get('handle')).trim(),platform:String(form.get('platform')),email,shipping_address:[form.get('street'),`${form.get('city')}, ${form.get('state')} ${form.get('zip')}`].join('\n'),brands});setDone(true)}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 return <div className="onboard-page"><div className="onboard-top"><span className="brand-mark">LB<span>·</span></span><span className="eyebrow">LOUISVILLE BRANDS</span></div><div className="onboard-layout"><div className="onboard-intro"><p className="eyebrow">CREATOR ONBOARDING</p><h1>Let's get the details right.</h1><p>Share your contact and shipping information for the brand partnerships you're working on.</p><div className="onboard-aside"><span>01 / 02</span><strong>Your details</strong><small>Only the brands you select receive your information.</small></div></div><div className="onboard-card">{done?<div className="success-state"><CheckCircle2 size={38}/><p className="eyebrow">ALL SET</p><h2>Thank you for joining us.</h2><p>Your information has been received. The Louisville Brands team will take it from here.</p></div>:<form onSubmit={e=>void submit(e)}><p className="eyebrow">CREATOR DETAILS</p><h2>Tell us about yourself</h2><div className="form-grid"><label className="span-2">Full name <input name="full_name" autoComplete="name" required placeholder="Your full name"/></label><label>Social handle <input name="handle" required placeholder="@yourhandle"/></label><label>Platform <select name="platform" required defaultValue=""><option value="" disabled>Select platform</option>{PLATFORM.map(p=><option key={p}>{p}</option>)}</select></label><label className="span-2">Email <input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label></div><div className="form-divider"/><p className="eyebrow">SHIPPING DETAILS</p><div className="form-grid"><label className="span-2">Street address <input name="street" autoComplete="street-address" required placeholder="Street address"/></label><label>City <input name="city" autoComplete="address-level2" required placeholder="City"/></label><label>State <input name="state" autoComplete="address-level1" required placeholder="State"/></label><label className="span-2">ZIP code <input name="zip" autoComplete="postal-code" required placeholder="ZIP code"/></label></div><div className="form-divider"/><fieldset className="brand-choices"><legend className="eyebrow">BRANDS YOU'RE WORKING WITH · SELECT ALL THAT APPLY</legend>{BRANDS.map(b=><label key={b}><input type="checkbox" checked={brands.includes(b)} onChange={()=>toggle(b)}/><span>{brandName[b]}</span></label>)}</fieldset><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary submit" disabled={busy}>{busy?'Submitting…':'Submit details'} <ArrowRight size={17}/></button><p className="privacy">Your details are shared only with the Louisville Brands team.</p></form>}</div></div></div>
}
