import { useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { AlertTriangle, Plus, Trash2 } from 'lucide-react'
import { DataTable, type GridColumn } from '../components/DataTable'
import { Brand, brandName, BRANDS, CARRIER, CONTACT, DELIVERABLE, emailValid, fieldWarnings, OutreachRow, PLATFORM, qualifies } from '../lib/model'
import { useStore } from '../lib/store'
const specs:{key:keyof OutreachRow;label:string;type:string;options?:string[];width?:number}[]=[
 {key:'creator_name',label:'Creator Name',type:'text',width:190},{key:'date_first_contacted',label:'Date First Contacted',type:'date',width:185},{key:'handle_raw',label:'Handle',type:'text',width:170},{key:'platform',label:'Platform',type:'select',options:PLATFORM},{key:'followers',label:'Followers',type:'number',width:120},{key:'email',label:'Email',type:'email',width:220},{key:'segments',label:'Segments',type:'tags',width:210},{key:'contact_status',label:'Contact Status',type:'select',options:CONTACT,width:175},{key:'deliverable_ask',label:'Deliverable / Ask',type:'text',width:240},{key:'shipping_address',label:'Shipping Address',type:'textarea',width:250},{key:'product_sku_sent',label:'Product / SKU Sent',type:'text',width:195},{key:'tracking_number',label:'Sample Tracking Number',type:'tracking',width:225},{key:'deliverable_status',label:'Deliverable Status',type:'select',options:DELIVERABLE,width:190},{key:'content_link',label:'Content Link',type:'url',width:210},{key:'date_posted',label:'Date Posted',type:'date',width:155},{key:'partnership_terms',label:'Partnership Terms',type:'textarea',width:230},{key:'ad_code',label:'Ad Code',type:'text',width:155},{key:'notes',label:'Notes',type:'textarea',width:250}
]
function Editor({row,spec,onSave}:{row:OutreachRow;spec:typeof specs[number];onSave:(changes:Partial<OutreachRow>)=>Promise<void>}) {
 const key=spec.key;const initial=key==='segments'?(row.segments||[]).join(', '):String(row[key]??'')
 const [draft,setDraft]=useState(initial),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false)
 const [tracking,setTracking]=useState(false)
 const save=async()=>{if(!editing)return;setEditing(false);const value=draft.trim();if(value===initial)return
 if(key==='email'&&value&&!emailValid(value)){window.alert('Enter a valid email address.');setDraft(initial);return}
 if(key==='content_link'&&value){try{const url=new URL(value);if(!['http:','https:'].includes(url.protocol))throw new Error()}catch{window.alert('Enter a valid http or https URL.');setDraft(initial);return}}
 const change=spec.type==='number'?(value?Number(value):null):spec.type==='tags'?value.split(',').map(s=>s.trim()).filter(Boolean):value||null
 setBusy(true);try{await onSave({[key]:change} as Partial<OutreachRow>)}catch(err){window.alert((err as Error).message);setDraft(initial)}finally{setBusy(false)}}
 if(spec.type==='tracking')return <div className="tracking-cell"><button className="cell-button" onClick={()=>setTracking(!tracking)}>{row.tracking_number||'Add tracking'} <span>⌄</span></button>{tracking&&<div className="tracking-popover"><label>Carrier<select value={row.tracking_carrier||''} onChange={e=>void onSave({tracking_carrier:e.target.value||null})}><option value="">Unknown</option>{CARRIER.map(v=><option key={v}>{v}</option>)}</select></label><label>Tracking number<input defaultValue={row.tracking_number||''} onBlur={e=>void onSave({tracking_number:e.target.value})}/></label><label>Est. delivery<input type="date" defaultValue={row.tracking_est_delivery||''} onChange={e=>void onSave({tracking_est_delivery:e.target.value||null})}/></label><label className="checkline"><input type="checkbox" checked={row.tracking_delivered} onChange={e=>void onSave({tracking_delivered:e.target.checked})}/> Delivered</label></div>}</div>
 if(spec.type==='select')return <select className="cell-select" aria-label={spec.label} value={String(row[key]||'')} onChange={e=>void onSave({[key]:e.target.value||null} as Partial<OutreachRow>)}><option value="">Select…</option>{spec.options?.map(v=><option key={v}>{v}</option>)}</select>
 if(spec.type==='textarea'&&editing)return <textarea className="cell-input expanded" aria-label={spec.label} autoFocus value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>void save()} onKeyDown={e=>{if(e.key==='Escape'){setEditing(false);setDraft(initial)}}}/>
 if(!editing)return <button className={`cell-button ${busy?'saving':''}`} title={initial||`Add ${spec.label}`} onClick={()=>setEditing(true)}>{spec.type==='url'&&initial?<a href={initial} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>{initial}</a>:spec.type==='date'&&initial?new Date(`${initial}T12:00:00`).toLocaleDateString():initial||<span className="placeholder">Add {spec.label.toLowerCase()}</span>}</button>
 return <input autoFocus className="cell-input" aria-label={spec.label} type={spec.type==='tags'?'text':spec.type} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>void save()} onKeyDown={e=>{if(e.key==='Enter'){e.currentTarget.blur()}if(e.key==='Escape'){setEditing(false);setDraft(initial)}}}/>
}
export function Outreach(){const {brand:slug}=useParams(),brand=BRANDS.includes(slug as Brand)?slug as Brand:'ljco';const {rows,update,add,remove,role,loading}=useStore();const [notice,setNotice]=useState('');const data=useMemo(()=>rows.filter(r=>r.brand===brand),[rows,brand]);const qualified=data.filter(qualifies).length
 const columns=useMemo<GridColumn<OutreachRow>[]>(()=>specs.map((s,i)=>({key:s.key,label:`${i+1} ${s.label}`,width:s.width||170,trigger:i===9||i===12,render:row=><Editor key={`${row.id}:${String(row[s.key])}`} row={row} spec={s} onSave={changes=>update(row.id,changes)}/>})),[update])
 const leading=(row:OutreachRow)=>{const warnings=fieldWarnings(row,data);return <div className="row-indicators">{qualifies(row)&&<span className="qualify-dot" title="In Creator Database"/>}{warnings.length>0&&<span title={warnings.join('\n')} aria-label={warnings.join(' ')}><AlertTriangle size={16} className="warn-icon"/></span>}{role==='admin'&&<button className="delete-row" aria-label={`Delete ${row.creator_name||'row'}`} title="Delete row" onClick={async()=>{if(window.confirm(`Delete ${row.creator_name||'this row'} from ${brandName[brand]}?`))try{await remove(row.id)}catch(err){setNotice((err as Error).message)}}}><Trash2 size={15}/></button>}</div>}
 return <><div className="page-heading"><div><p className="eyebrow">OUTREACH / {brandName[brand].toUpperCase()}</p><h1>{brandName[brand]} <span className="chip chip-ok">18 FIELDS</span></h1><p>Track conversations, samples, and content for this brand. Changes save when you leave a field.</p></div><button className="primary" onClick={()=>void add(brand).catch(e=>setNotice(e.message))}><Plus size={17}/> Add row</button></div><div className="metric-strip"><div><span>CONTACTS</span><strong>{data.length.toString().padStart(2,'0')}</strong></div><div><span>IN CREATOR DATABASE</span><strong>{qualified.toString().padStart(2,'0')}</strong></div><div><span>AWAITING CONTENT</span><strong>{data.filter(r=>r.deliverable_status==='In Progress').length.toString().padStart(2,'0')}</strong></div><div className="strip-caption">One shared view for your team's work.</div></div>{notice&&<div className="error-banner" role="alert">{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}
 <section className="panel"><div className="panel-top"><div><p className="eyebrow">WORKING LIST</p><h2>Outreach records</h2></div><span className="panel-count">{data.length} RECORDS</span></div>{loading?<p className="loading">Loading records…</p>:<DataTable data={data} columns={columns} leading={leading} filename={`${brand}-outreach.csv`} empty="No contacts yet. Add a row to begin."/>}<p className="table-legend"><span className="legend-line"/> Underlined = trigger column for the Creator Database pull. <span className="legend-dot"/> Qualifies now. <AlertTriangle size={14}/> Review warning.</p></section></>
}
