import {json,service,staff,isBrand} from '../_shared/common.ts'
const columns=['creator_name','date_first_contacted','handle_raw','platform','followers','email','segments','contact_status','deliverable_ask','shipping_address','product_sku_sent','tracking_carrier','tracking_number','tracking_est_delivery','tracking_delivered','deliverable_status','content_link','date_posted','partnership_terms','ad_code','notes']
Deno.serve(async req=>{if(req.method==='OPTIONS')return json({},200);const user=await staff(req,true);if(!user)return json({error:'Administrator access required'},403)
 try{const {brand,rows}=await req.json();if(!isBrand(brand)||!Array.isArray(rows)||rows.length>500)return json({error:'Invalid import'},400);const db=service();let count=0
 for(const raw of rows){const record:Record<string,unknown>={brand,source:'import',created_by:user.id};for(const key of columns)if(raw[key]!==undefined)record[key]=raw[key];const email=String(record.email||'').toLowerCase().trim(),handle=String(record.handle_raw||'').trim().replace(/^@+/,'').toLowerCase();const [byEmail,byHandle]=await Promise.all([email?db.from('outreach_rows').select('*').eq('brand',brand).eq('email',email).limit(2):Promise.resolve({data:[],error:null}),handle?db.from('outreach_rows').select('*').eq('brand',brand).eq('handle_normalized',handle).limit(2):Promise.resolve({data:[],error:null})]);if(byEmail.error)throw byEmail.error;if(byHandle.error)throw byHandle.error;const matches=[...(byEmail.data||[]),...(byHandle.data||[])];
 const match=matches?.find(r=>r.email?.toLowerCase()===email&&email||r.handle_normalized===handle&&handle)
 if(match&&raw._duplicateAction==='merge'){const changes:Record<string,unknown>={};for(const [key,value] of Object.entries(record))if(!['brand','source','created_by'].includes(key)&&(match[key]===null||match[key]===''||Array.isArray(match[key])&&match[key].length===0))changes[key]=value;if(Object.keys(changes).length){const {error}=await db.from('outreach_rows').update(changes).eq('id',match.id);if(error)throw error}}
 else if(!match||raw._duplicateAction==='import'){const {error}=await db.from('outreach_rows').insert(record);if(error)throw error}
 count++}return json({count})}catch(e){return json({error:(e as Error).message},500)}})
