import { useMemo, useState, type ReactNode } from 'react'
import { flexRender, getCoreRowModel, getFilteredRowModel, getSortedRowModel, useReactTable, type ColumnDef, type SortingState } from '@tanstack/react-table'
import { ArrowDown, ArrowUp, Columns3, Download, Search } from 'lucide-react'
import { csv, downloadCsv } from '../lib/model'
export interface GridColumn<T> { key:keyof T & string; label:string; render?:(row:T)=>ReactNode; sortable?:boolean; trigger?:boolean; width?:number }
export function DataTable<T extends object>({data,columns,filename,searchPlaceholder='Search records',filters,leading,empty='No records yet.'}:{data:T[];columns:GridColumn<T>[];filename:string;searchPlaceholder?:string;filters?:ReactNode;leading?:(row:T)=>ReactNode;empty?:string}) {
 const [search,setSearch]=useState(''),[sorting,setSorting]=useState<SortingState>([]),[hidden,setHidden]=useState<Record<string,boolean>>({}),[showColumns,setShowColumns]=useState(false),[columnFilter,setColumnFilter]=useState<Record<string,string>>({})
 const tableColumns=useMemo<ColumnDef<T>[]>(()=>[
 ...(leading?[{id:'_indicator',header:'',cell:({row}:{row:{original:T}})=>leading(row.original),enableSorting:false,size:44} as ColumnDef<T>]:[]),
 ...columns.map(c=>({id:c.key,accessorFn:(row:T)=>row[c.key],header:c.label,cell:({row}:{row:{original:T}})=>c.render?c.render(row.original):String(row.original[c.key]??'None'),enableSorting:c.sortable!==false,size:c.width||160} as ColumnDef<T>))], [columns,leading])
 const filtered=useMemo(()=>data.filter(row=>{const searchMatch=!search||Object.values(row).some(v=>String(Array.isArray(v)?v.join(' '):v??'').toLowerCase().includes(search.toLowerCase()));return searchMatch&&Object.entries(columnFilter).every(([key,val])=>!val||String(row[key as keyof T]??'').toLowerCase().includes(val.toLowerCase()))}),[data,search,columnFilter])
 const table=useReactTable({data:filtered,columns:tableColumns,state:{sorting,columnVisibility:hidden},onSortingChange:setSorting,onColumnVisibilityChange:setHidden,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel()})
 const visible=columns.filter(c=>!hidden[c.key]);return <><div className="table-toolbar"><div className="search-box"><Search size={17}/><input aria-label={searchPlaceholder} placeholder={searchPlaceholder} value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌕</kbd></div>{filters}<div className="toolbar-spacer"/><div className="column-menu-wrap"><button className="button ghost" onClick={()=>setShowColumns(!showColumns)} aria-expanded={showColumns}><Columns3 size={16}/> Columns</button>{showColumns&&<div className="column-menu"><div className="eyebrow">SHOW COLUMNS</div>{columns.map(c=><label key={c.key}><input type="checkbox" checked={!hidden[c.key]} onChange={()=>setHidden({...hidden,[c.key]:!hidden[c.key]})}/>{c.label}</label>)}</div>}</div><button className="button ghost" onClick={()=>downloadCsv(filename,csv(table.getSortedRowModel().rows.map(r=>r.original) as Record<string,unknown>[],visible.map(c=>({key:c.key,label:c.label}))))}><Download size={16}/> Export CSV</button></div>
 <div className="grid-wrap"><table className="data-table"><thead>{table.getHeaderGroups().map(group=><tr key={group.id}>{group.headers.map(h=>{const col=columns.find(c=>c.key===h.column.id);return <th key={h.id} style={{minWidth:h.getSize(),width:h.getSize()}}><button className={`th-sort ${col?.trigger?'trigger':''}`} onClick={h.column.getToggleSortingHandler()} disabled={!h.column.getCanSort()}>{flexRender(h.column.columnDef.header,h.getContext())}{h.column.getIsSorted()==='asc'?<ArrowUp size={12}/>:h.column.getIsSorted()==='desc'?<ArrowDown size={12}/>:null}</button>{col&&<input className="column-filter" aria-label={`Filter ${col.label}`} placeholder="Filter…" value={columnFilter[col.key]||''} onChange={e=>setColumnFilter({...columnFilter,[col.key]:e.target.value})}/>}</th>})}</tr>)}</thead><tbody>{table.getRowModel().rows.length?table.getRowModel().rows.map(row=><tr key={row.id}>{row.getVisibleCells().map(cell=><td key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>):<tr><td colSpan={table.getVisibleLeafColumns().length} className="empty-table">{empty}</td></tr>}</tbody></table></div><div className="table-footer"><span>{table.getRowModel().rows.length} of {data.length} records</span><span>Scroll horizontally to view all fields</span></div></>
}
