import { useEffect, useState } from 'react'
import { Link, NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom'
import { ChevronDown, Database, LogOut, Menu, Moon, Settings, Sun, Upload, X } from 'lucide-react'
import { connected, supabase } from '../lib/client'
import { useStore } from '../lib/store'
const sections=[{label:'Trybe creators · API',links:[['LJCo','/trybe/ljco','Read-only'],['Gym Snack','/trybe/gym_snack','Read-only'],['Pumps','/trybe/pumps','Read-only']]},{label:'Outreach · you maintain',links:[['Louisville Jerky','/outreach/ljco',''],['Pumps','/outreach/pumps',''],['Gym Snack','/outreach/gym_snack','']]},{label:'Database',links:[['Creator Database','/creators','Derived']]},{label:'Reference',links:[['How the pull works','/reference','']]}]
export function Shell(){const {demo,session,role,error}=useStore();const navigate=useNavigate(),location=useLocation();const [open,setOpen]=useState(false),[theme,setTheme]=useState(()=>{try{return localStorage.getItem('lb-theme')||'system'}catch{return 'system'}})
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('lb-theme',theme)}catch{}},[theme]);useEffect(()=>{setOpen(false);try{localStorage.setItem('lb-last-tab',location.pathname)}catch{}},[location.pathname]);
 if(connected&&!session)return <main className="login-page"><div className="login-card"><span className="brand-mark">LB<span>·</span></span><p className="eyebrow">Louisville Brands · internal workspace</p><h1>Influencer outreach, all in one place.</h1><p>Sign in with your Louisville Brands Google account to view outreach and creator records.</p><button className="primary" onClick={()=>void supabase?.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+'/outreach/ljco'}})}>Continue with Google</button><p className="subtle">Access is limited to @louisvillebrands.com accounts.</p></div></main>
 return <div className="app-shell"><button className="mobile-menu icon-btn" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu size={20}/></button>{open&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}
 <aside className={`sidebar ${open?'open':''}`}><div className="sidebar-top"><Link to="/outreach/ljco" className="brand"><span className="brand-symbol">LB<span>·</span></span><span>LOUISVILLE<br/>BRANDS</span></Link><button className="icon-btn mobile-close" aria-label="Close navigation" onClick={()=>setOpen(false)}><X size={18}/></button></div>
 <div className="sidebar-rule"/><nav aria-label="Main navigation">{sections.map(section=><div className="nav-section" key={section.label}><div className="nav-label">{section.label}</div>{section.links.map(([name,path,flag])=><NavLink to={path} key={path} className={({isActive})=>`nav-link ${isActive?'active':''}`}><span className="nav-dot"/><span className="nav-text">{name}</span>{flag&&<span className="nav-flag">{flag}</span>}</NavLink>)}</div>)}</nav>
 <div className="sidebar-bottom"><div className="sidebar-rule"/><div className="sidebar-actions">{role==='admin'&&<><NavLink to="/settings" className="sidebar-action"><Settings size={16}/> Settings</NavLink><NavLink to="/import" className="sidebar-action"><Upload size={16}/> Import</NavLink></>}<button className="sidebar-action" onClick={()=>connected?void supabase?.auth.signOut().then(()=>navigate('/outreach/ljco')):window.alert('Demo mode has no account session.')}><LogOut size={16}/> Sign out</button></div><div className="sidebar-user"><span className="avatar">{demo?'D':session?.user.email?.[0].toUpperCase()}</span><span><strong>{demo?'Preview workspace':session?.user.email}</strong><small>{demo?'Sample data · local only':role==='admin'?'Administrator':'Team member'}</small></span></div></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumbs"><span>WORKSPACE</span><span className="slash">/</span><span>{location.pathname.split('/')[1]?.replace('_',' ')||'outreach'}</span></div><div className="topbar-right">{demo&&<span className="demo-pill">LOCAL PREVIEW</span>}<label className="theme-select"><span className="sr-only">Theme</span>{theme==='dark'?<Moon size={16}/>:<Sun size={16}/>}<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select><ChevronDown size={12}/></label></div></header>{error&&<div className="error-banner" role="alert">{error}</div>}<main className="main-content"><Outlet/></main><footer className="app-footer"><Database size={14}/> Louisville Brands · Outreach workspace <span>Internal use</span></footer></div></div>
}
