import {json,service,staff,brands,isBrand,decrypt,type Brand} from '../_shared/common.ts'
import {adapter,type TrybeBrandConfig} from '../_shared/trybe.ts'
async function config(brand:Brand):Promise<TrybeBrandConfig>{const suffix=brand==='gym_snack'?'GYMSNACK':brand.toUpperCase();const db=service();const {data}=await db.from('brand_integrations').select('api_key_ciphertext,account_id').eq('brand',brand).maybeSingle();const apiKey=data?.api_key_ciphertext?await decrypt(data.api_key_ciphertext):Deno.env.get(`TRYBE_API_KEY_${suffix}`)||'';if(!apiKey&&Deno.env.get('TRYBE_USE_MOCK')!=='true')throw new Error(`API key for ${brand} is not configured`);return {brand,apiKey,accountId:data?.account_id||Deno.env.get(`TRYBE_ACCOUNT_ID_${suffix}`)}}
export async function syncBrand(brand:Brand){const db=service();const {data:run,error:runError}=await db.from('trybe_sync_runs').insert({brand}).select('id').single();if(runError)throw runError
 try{const creators=await adapter().fetchCreators(await config(brand));const ids=creators.map(c=>c.trybe_creator_id);const at=new Date().toISOString();const payload=creators.map(c=>({...c,brand,active:true,synced_at:at}));if(payload.length){const {error}=await db.from('trybe_creators').upsert(payload,{onConflict:'brand,trybe_creator_id'});if(error)throw error}
 const {data:existing,error:readError}=await db.from('trybe_creators').select('trybe_creator_id').eq('brand',brand).eq('active',true);if(readError)throw readError;const stale=(existing||[]).map(c=>c.trybe_creator_id).filter(id=>!ids.includes(id));if(stale.length){const {error}=await db.from('trybe_creators').update({active:false,synced_at:at}).eq('brand',brand).in('trybe_creator_id',stale);if(error)throw error}
 await db.from('trybe_sync_runs').update({finished_at:at,ok:true,rows_upserted:payload.length}).eq('id',run.id);return {brand,ok:true,rows_upserted:payload.length}}
 catch(e){const error=(e as Error).message;await db.from('trybe_sync_runs').update({finished_at:new Date().toISOString(),ok:false,error,rows_upserted:0}).eq('id',run.id);return {brand,ok:false,error}}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-cron-secret'}});if(req.method!=='POST')return json({error:'POST required'},405)
 const cron=Deno.env.get('SYNC_CRON_SECRET');const scheduled=Boolean(cron&&req.headers.get('x-cron-secret')===cron);const user=scheduled?null:await staff(req);if(!scheduled&&!user)return json({error:'Unauthorized'},401)
 try{const body=await req.json().catch(()=>({}));if(body.brand&&!isBrand(body.brand))return json({error:'Invalid brand'},400);if(body.brand)return json(await syncBrand(body.brand));const db=service();const {data:setting}=await db.from('app_settings').select('sync_interval_hours').single();const hours=setting?.sync_interval_hours||6;const results=await Promise.all(brands.map(async brand=>{if(scheduled){const {data:last}=await db.from('trybe_sync_runs').select('started_at').eq('brand',brand).order('started_at',{ascending:false}).limit(1).maybeSingle();if(last&&Date.now()-new Date(last.started_at).getTime()<hours*3600000)return {brand,skipped:true}}return syncBrand(brand)}));return json({results})}catch(e){return json({error:(e as Error).message},500)}})
