import {json,service,staff,isBrand,encrypt} from '../_shared/common.ts'
import {adapter} from '../_shared/trybe.ts'
Deno.serve(async req=>{if(req.method==='OPTIONS')return json({},200);const user=await staff(req,true);if(!user)return json({error:'Administrator access required'},403)
 try{const body=await req.json(),db=service();if(body.action==='list'){const {data:accounts,error}=await db.from('brand_integrations').select('brand,api_key_last4,account_id');if(error)throw error;return json({accounts})}
 if(body.action==='schedule'){const hours=Number(body.hours);if(!Number.isInteger(hours)||hours<1||hours>24)return json({error:'Invalid interval'},400);const {error}=await db.from('app_settings').update({sync_interval_hours:hours}).eq('id',true);if(error)throw error;return json({message:`Sync interval set to ${hours} hours.`})}
 if(body.action==='role'){if(!['admin','member'].includes(body.role))return json({error:'Invalid role'},400);if(body.userId===user.id&&body.role!=='admin')return json({error:'You cannot remove your own admin role.'},400);const {error}=await db.from('user_profiles').update({role:body.role}).eq('user_id',body.userId);if(error)throw error;return json({message:'Role updated.'})}
 if(!isBrand(body.brand))return json({error:'Invalid brand'},400);const brand=body.brand
 if(body.action==='save_key'){const apiKey=String(body.apiKey||'').trim();if(!apiKey)return json({error:'An API key is required.'},400);const cipher=await encrypt(apiKey);const {error}=await db.from('brand_integrations').upsert({brand,api_key_ciphertext:cipher,api_key_last4:apiKey.slice(-4),account_id:String(body.accountId||'')||null,updated_at:new Date().toISOString()});if(error)throw error;return json({message:'Credentials saved securely.'})}
 if(body.action==='test'){const {data}=await db.from('brand_integrations').select('api_key_ciphertext,account_id').eq('brand',brand).maybeSingle();const suffix=brand==='gym_snack'?'GYMSNACK':brand.toUpperCase();const {decrypt}=await import('../_shared/common.ts');const apiKey=data?.api_key_ciphertext?await decrypt(data.api_key_ciphertext):Deno.env.get(`TRYBE_API_KEY_${suffix}`)||'';return json(await adapter().testConnection({brand,apiKey,accountId:data?.account_id||undefined}))}
 if(body.action==='sync'){const response=await fetch(`${Deno.env.get('SUPABASE_URL')}/functions/v1/trybe-sync`,{method:'POST',headers:{Authorization:req.headers.get('Authorization')||'',apikey:Deno.env.get('SUPABASE_ANON_KEY')||'','Content-Type':'application/json'},body:JSON.stringify({brand})});const result=await response.json();return json({message:result.ok?`Synced ${result.rows_upserted} creators.`:`Sync failed: ${result.error||'Unknown error'}`})}
 return json({error:'Unknown action'},400)}catch(e){return json({error:(e as Error).message},500)}})
